version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:9BDTKMaZVGZ5z1VVf2Gpbu2UYYWuJASnyoJv0hk2jeM=
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
