# fly.toml app configuration file generated for bot-project-lingering-snow-8492 on 2024-12-26T12:22:03+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-project'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
